/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Antrian;
import Model.Antrian.DAOAntrian;
import Model.Antrian.ModelAntrian;
import Model.Antrian.ModelTableAntrian;
import Model.Pasien.DAOPasien;
import Model.Pasien.ModelPasien;
import Model.Dokter.DAODokter;
import Model.Dokter.ModelDokter;
import Model.Obat.DAOObat;
import Model.Obat.ModelObat;

import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.*;
import java.sql.Date;
import java.time.LocalDate;
import java.util.*;
import java.util.List;
/**
 *
 * @author Acer
 */
public class LihatAntrian extends javax.swing.JFrame {
    private DAOAntrian  daoAntrian  = new DAOAntrian();
    private DAOPasien   daoPasien   = new DAOPasien();
    private DAODokter   daoDokter   = new DAODokter();
    private DAOObat     daoObat     = new DAOObat();

    // ── Data referensi ────────────────────────────────────
    private List<ModelPasien> listPasien = new ArrayList<>();
    private List<ModelDokter> listDokter = new ArrayList<>();
    private List<ModelObat>   listObat   = new ArrayList<>();

    // ── Map ID → Nama (untuk tampilan tabel) ─────────────
    private Map<Integer, String> mapPasien = new HashMap<>();
    private Map<Integer, String> mapDokter = new HashMap<>();
    private Map<Integer, String> mapObat   = new HashMap<>();

    // ── Model tabel ───────────────────────────────────────
    private ModelTableAntrian tableModel = new ModelTableAntrian();

    // ── ID antrian yang sedang dipilih ────────────────────
    private int selectedId = -1;

    // ── Status yang tersedia ──────────────────────────────
    private static final String[] STATUS_LIST = {
        "Antri", "Dipanggil", "Sedang Ditangani", "Sudah Ditangani", "Batal"
    };
   private void loadReferensi() {
        try {
            // Pasien
            listPasien = daoPasien.getAll();
            cmbPasien.removeAllItems();
            mapPasien.clear();
            for (ModelPasien p : listPasien) {
                cmbPasien.addItem(p.getId() + " - " + p.getNama());
                mapPasien.put(p.getId(), p.getNama());
            }

            // Dokter
            listDokter = daoDokter.getAll();
            cmbDokter.removeAllItems();
            mapDokter.clear();
            for (ModelDokter d : listDokter) {
                cmbDokter.addItem(d.getId() + " - dr. " + d.getNama());
                mapDokter.put(d.getId(), "dr. " + d.getNama());
            }

            // Obat
            listObat = daoObat.getAll();
            cmbObat.removeAllItems();
            mapObat.clear();
            for (ModelObat o : listObat) {
                cmbObat.addItem(o.getId() + " - " + o.getNama());
                mapObat.put(o.getId(), o.getNama());
            }

        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this,
                "Gagal load data referensi:\n" + e.getMessage(),
                "Error DB", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void loadTabel() {
        try {
            tableModel.setData(daoAntrian.getAll(), mapPasien, mapDokter, mapObat);
            tableAntrian.setModel(tableModel);
            tableModel.fireTableDataChanged();
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error DB", JOptionPane.ERROR_MESSAGE);
        }
    }
    public LihatAntrian() {
        initComponents();
        tableAntrian.setModel(tableModel);
        loadReferensi();
        loadTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbPasien = new javax.swing.JComboBox<>();
        cmbDokter = new javax.swing.JComboBox<>();
        cmbObat = new javax.swing.JComboBox<>();
        txtTanggal = new javax.swing.JTextField();
        txtKeluhan = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAntrian = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        btnDaftar = new javax.swing.JButton();
        btnUbahStatus = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Antrian Pasien");

        jLabel2.setText("Form Pendaftaran Antrian");

        jLabel3.setText("Pasien");

        jLabel4.setText("Dokter");

        jLabel5.setText("Obat");

        jLabel6.setText("Tanggal (yyyy-mm-dd)");

        jLabel7.setText("Keluhan");

        jLabel8.setText("Status");

        cmbPasien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        cmbPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPasienActionPerformed(evt);
            }
        });

        cmbDokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        cmbObat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        txtTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalActionPerformed(evt);
            }
        });

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Antri", "Dipanggil", "Sedang Ditangani", "Batal"}));

        tableAntrian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Pasien", "Dokter", "Obat", "Tanggal", "Keluhan", "Status"
            }
        ));
        tableAntrian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAntrianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAntrian);

        jLabel9.setText("Daftar Pasien");

        btnDaftar.setText("DAFTAR");
        btnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarActionPerformed(evt);
            }
        });

        btnUbahStatus.setText("UBAH STATUS");
        btnUbahStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahStatusActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(474, 474, 474)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbObat, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKeluhan, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUbahStatus)
                                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addContainerGap(53, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtKeluhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDaftar)
                    .addComponent(btnUbahStatus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnDelete))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPasienActionPerformed

    private void txtTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new View.MainView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarActionPerformed
        selectedId = -1; // paksa mode INSERT
        ModelAntrian a = formKeAntrian();
        if (a == null) return;
        try {
            daoAntrian.insert(a);
            loadTabel();
            bersihForm();
            JOptionPane.showMessageDialog(this, "Antrian berhasil didaftarkan!", "Sukses",
                JOptionPane.INFORMATION_MESSAGE);
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDaftarActionPerformed

    private void btnUbahStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahStatusActionPerformed
        if (selectedId < 0) {
            JOptionPane.showMessageDialog(this, "Pilih antrian dari tabel terlebih dahulu!",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String statusBaru = (String) cmbStatus.getSelectedItem();
        try {
            daoAntrian.updateStatus(selectedId, statusBaru);
            loadTabel();
            JOptionPane.showMessageDialog(this,
                "Status antrian berhasil diubah menjadi: " + statusBaru, "Sukses",
                JOptionPane.INFORMATION_MESSAGE);
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUbahStatusActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (selectedId < 0) {
            JOptionPane.showMessageDialog(this, "Pilih antrian dari tabel terlebih dahulu!",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int konfirmasi = JOptionPane.showConfirmDialog(this,
            "Yakin ingin menghapus antrian ini?", "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            try {
                daoAntrian.delete(selectedId);
                loadTabel();
                bersihForm();
            } catch (RuntimeException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tableAntrianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAntrianMouseClicked
        int row = tableAntrian.getSelectedRow();
        if (row < 0) return;

        selectedId = (Integer) tableModel.getValueAt(row, 0);

        // cari antrian dari DAO berdasarkan ID
        try {
            for (ModelAntrian a : daoAntrian.getAll()) {
                if (a.getId().equals(selectedId)) {
                    // set combobox pasien
                    for (int i = 0; i < listPasien.size(); i++)
                        if (listPasien.get(i).getId().equals(a.getIdPasien())) {
                            cmbPasien.setSelectedIndex(i); break;
                        }
                    // set combobox dokter
                    for (int i = 0; i < listDokter.size(); i++)
                        if (listDokter.get(i).getId().equals(a.getIdDokter())) {
                            cmbDokter.setSelectedIndex(i); break;
                        }
                    // set combobox obat
                    for (int i = 0; i < listObat.size(); i++)
                        if (listObat.get(i).getId().equals(a.getIdObat())) {
                            cmbObat.setSelectedIndex(i); break;
                        }
                    txtTanggal.setText(a.getTanggal().toString());
                    txtKeluhan.setText(a.getKeluhan());
                    cmbStatus.setSelectedItem(a.getStatus());
                    break;
                }
            }
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tableAntrianMouseClicked
    private ModelAntrian formKeAntrian() {
        if (listPasien.isEmpty() || listDokter.isEmpty() || listObat.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Data pasien, dokter, atau obat belum ada!\nSilakan tambahkan terlebih dahulu.",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return null;
        }

        int idxPasien = cmbPasien.getSelectedIndex();
        int idxDokter = cmbDokter.getSelectedIndex();
        int idxObat   = cmbObat.getSelectedIndex();

        if (idxPasien < 0 || idxDokter < 0 || idxObat < 0) {
            JOptionPane.showMessageDialog(this, "Pilih Pasien, Dokter, dan Obat!",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return null;
        }

        String tglStr  = txtTanggal.getText().trim();
        String keluhan = txtKeluhan.getText().trim();
        String status  = (String) cmbStatus.getSelectedItem();

        if (tglStr.isEmpty() || keluhan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tanggal dan Keluhan wajib diisi!",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return null;
        }

        Date tanggal;
        try {
            tanggal = Date.valueOf(tglStr);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, "Format tanggal harus yyyy-MM-dd\nContoh: 2025-05-24",
                "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        int idPasien = listPasien.get(idxPasien).getId();
        int idDokter = listDokter.get(idxDokter).getId();
        int idObat   = listObat.get(idxObat).getId();

        if (selectedId > 0)
            return new ModelAntrian(selectedId, idPasien, idDokter, idObat, tanggal, keluhan, status);
        else
            return new ModelAntrian(idPasien, idDokter, idObat, tanggal, keluhan, status);
    }
    private void bersihForm() {
        selectedId = -1;
        if (cmbPasien.getItemCount() > 0) cmbPasien.setSelectedIndex(0);
        if (cmbDokter.getItemCount() > 0) cmbDokter.setSelectedIndex(0);
        if (cmbObat.getItemCount()   > 0) cmbObat.setSelectedIndex(0);
        txtTanggal.setText(Date.valueOf(LocalDate.now()).toString());
        txtKeluhan.setText("");
        cmbStatus.setSelectedIndex(0);
        tableAntrian.clearSelection();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LihatAntrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LihatAntrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LihatAntrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LihatAntrian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LihatAntrian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDaftar;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUbahStatus;
    private javax.swing.JComboBox<String> cmbDokter;
    private javax.swing.JComboBox<String> cmbObat;
    private javax.swing.JComboBox<String> cmbPasien;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAntrian;
    private javax.swing.JTextField txtKeluhan;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
